config/routes.rb
Rails.application.routes.draw do
  resources :places
  root 'places#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/place.rb
class Place < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    params = { term: 'food',
               # limit: 20
             }

    locale = { lang: 'en' }

    @places = Yelp.client.search('Chicago', params, locale).businesses.sample(3)

    byebug

    respond_to do |format|
      format.html { render :index }
      format.js   { @place = @places[0]; render :index }
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.fetch(:place, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FoodApp
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav
      .container
        = link_to "What do you want to eat? Idk.", root_path

    .container    
      = yield

app/views/places/_card.html.haml
.card{ class: "#{idx == 0 ? '' : 'hidden'}", data: { queue: "#{idx}" } }
  .card-image
    = image_tag place.image_url
  .card-content
    %h5.title= place.name
    .links 
      = link_to "#", class: "text-red dislike-button" do
        = icon 'times'
      = link_to place.mobile_url, target: "_blank", rel: "noopener noreferrer", class: "text-green" do
        = icon 'heart'

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
.row.center
  .col.s12.m8.l6.offset-s2.offset-l3
    .cards
      - @places.each_with_index do |place, idx|
        = render 'card', place: place, idx: idx

app/views/places/index.js.erb
$(".cards").html("<%= j render partial: 'card', locals: { place: @place } %>");

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_place_path(@place)
\|
= link_to 'Back', places_path